# Generated by Django 5.2.12 on 2026-04-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('master', 'Мастер'), ('player', 'Игрок')], default='player', max_length=50),
        ),
    ]
